# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies (requirements.txt)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 5
    reviewers:
      - "CloudITNow"  # My username for review
    assignees:
      - "CloudITNow"
    commit-message:
      prefix: "python"
      include: "scope"
    labels:
      - "dependencies"
      - "python"

  # Docker images in YAML file
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 3
    reviewers:
      - "CloudITNow"
    assignees:
      - "CloudITNow"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions - if have any action
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
      time: "15:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 2
    reviewers:
      - "CloudITNow"
    assignees:
      - "CloudITNow"
    commit-message:
      prefix: "actions"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
