version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/Project1-FlaskAppWithRedis"  # ← Poprawiona ścieżka
    schedule:
      interval: "daily"
      time: "16:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 5
    assignees:
      - "CloudITNow"
    commit-message:
      prefix: "python"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
  
  # Docker images
  - package-ecosystem: "docker"
    directory: "/Project1-FlaskAppWithRedis"  # ← Poprawiona ścieżka
    schedule:
      interval: "daily"
      time: "16:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 3
    assignees:
      - "CloudITNow"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
  
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "16:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 5
    assignees:
      - "CloudITNow"
    labels:
      - "dependencies"
      - "github-actions"