# Prod ENV
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
      env: prod
  template:
    metadata:
      labels:
        app: flask-app
        env: prod
    spec:
      containers:
      - name: flask-app
        image: flask-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis-service
        - name: ENVIRONMENT
          value: production
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
---
# Dev ENV
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
      env: dev
  template:
    metadata:
      labels:
        app: flask-app
        env: dev
    spec:
      containers:
      - name: flask-app
        image: flask-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis-service
        - name: ENVIRONMENT
          value: development
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
# Service for PROD ENV
apiVersion: v1
kind: Service
metadata:
  name: flask-prod-service
spec:
  type: NodePort
  selector:
    app: flask-app
    env: prod
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30005
---
# Service for DEV ENV
apiVersion: v1
kind: Service
metadata:
  name: flask-dev-service
spec:
  type: NodePort
  selector:
    app: flask-app
    env: dev
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30006